#! /usr/bin/env python

"""
Run it with:
$ python replace.py fasta.fa names output.fa
"""

import argparse
p = argparse.ArgumentParser()
p.add_argument('fasta_file')
p.add_argument('names_file')
p.add_argument('output')
args = p.parse_args()

names = {}
with open(args.names_file, 'r') as f:
    for line in f:
        old, new = line.split('\t')
        names[old] = new.strip()

with open(args.fasta_file, 'r') as f:
    with open(args.output, 'w') as output:
        for line in f:
            if line.startswith('>'):
                try:
                    line = '>' + names[line.strip()[1:]] + '\n'
                except KeyError:
                    pass
            output.write(line)
